### ISSUE TITLE
Popup menu bug

### ISSUE THREAD

**Issue by cbrt-x** [MonsterDruide1/TAS-Editor#21]
The popup menu behaves weirdly on start up, sometimes not working at all and sometimes really glitching out. I will attach 2 photos showing that. I have no idea why this happens. This also only seems to happen in the .jar 
![image](https://user-images.githubusercontent.com/79963380/117685615-6022f500-b1b6-11eb-8bbb-4c2d6ffc04bb.png)
![image](https://user-images.githubusercontent.com/79963380/117685658-6c0eb700-b1b6-11eb-9ec5-c39daa5da57f.png)

**Comment by MonsterDruide1** [comment]
Probably due to Look&Feel issues, so should be fixed as well in [this](https://github.com/Jadefalke2/TAS-editor/commit/62fb057300bd26f1f91c0a468fbe3b7e7cda1fe2) commit as well. At least I can't reproduce it anymore.
