### ISSUE TITLE
Column size of "Minus" and "Plus" as well as some others is wrong

### ISSUE THREAD

**Issue by cbrt-x** [MonsterDruide1/TAS-Editor#23]

**Comment by MonsterDruide1** [comment]
What do you define as wrong...?
The columns have the following widths:
```
int[] columnsWidth = {
	45,							  // frame number
	85, 85,									// sticks
	18, 18, 18, 18, 25, 25, 18, 18, 18, 18, 30, 30, 30, 30, 50, 50				 // buttons
		};
```
as defined in PianoRoll.java#102.

**Comment by cbrt-x** [comment]
Minus/Plus needs to be resized (this is like a 10 secs fix but i didnt have the time yet and I wanted to note it down)
