### ISSUE TITLE
Moving stick and centering does not cause correction

### ISSUE THREAD

**Issue by Rhinozz** [MonsterDruide1/TAS-Editor#25]
In both stick columns, clicking on an entry opens a popup menu.
![image](https://user-images.githubusercontent.com/68926744/117700356-e5e17900-b193-11eb-9436-54f5f5e6f4ed.png)
This image shows an entry in the right stick column starting at 0;0. It opens a popup window when clicked, and joystick can be moved. The box reflects that.
![image](https://user-images.githubusercontent.com/68926744/117700458-0ad5ec00-b194-11eb-9651-81a7c3ead127.png)
However, when clicking "center", the box does not change.
![image](https://user-images.githubusercontent.com/68926744/117700503-19bc9e80-b194-11eb-99f8-cdd7a087b78f.png)

**Comment by cbrt-x** [comment]
This also applies for "keep stick postion for n frames" the first frame, I don't know why
