### ISSUE TITLE
Undo/Redo break the script in major ways

### ISSUE THREAD

**Issue by cbrt-x** [MonsterDruide1/TAS-Editor#26]
1) Undo/redo doesn't work for a lot of stuff -> mainly line adding/removing

2) Undo/redo sometimes breaks for line adding/removing, corrupting the script

**Comment by MonsterDruide1** [comment]
Can't reproduce this. All my undo-redo testing works fine for me...

**Comment by cbrt-x** [comment]
After thorough testing I have come to the same conclusion. It seems to be fixed now, since I had reworked it before anyways. If theres any updates on this we can reopen this
