### ISSUE TITLE
Stick angle bug

### ISSUE THREAD

**Issue by cbrt-x** [MonsterDruide1/TAS-Editor#27]
Stick angle is negtive when y < 0 (Cartesian)

**Comment by MonsterDruide1** [comment]
What is the intended behaviour here? An angle between 180 and 360°?

**Comment by cbrt-x** [comment]
An angle between 0° (furthest right) to 360° (a full turn). Right now it messes up all angles between 181° and 360° (They are negative and have the wrong values)

**Comment by MonsterDruide1** [comment]
Would you define 90° as upwards or as downwards? So are you spinning clockwise or counter-clockwise?

**Comment by cbrt-x** [comment]
Upwards, so counterclockwise
