### ISSUE TITLE
Angle spinner behaves weirdly

### ISSUE THREAD

**Issue by cbrt-x** [MonsterDruide1/TAS-Editor#40]
The angle spinner sometimes increments in .5 - .7 steps it seems like 
no idea why

**Comment by MonsterDruide1** [comment]
Probably due to `Math.atan2` inaccuracies.

**Comment by MonsterDruide1** [comment]
It looks like **decreasing** the value works fine, but **increasing** leads to weird intervals...

**Comment by cbrt-x** [comment]
Yep, noticed that too. If you look at the X and Y spinners you can see exactly by how much they increase -> derive the cause fro  that?
