### ISSUE TITLE
R-Button error when recording inputs

### ISSUE THREAD

**Issue by JoniKauf** [MonsterDruide1/TAS-editor#49]
If you try recording inputs with f7 + ctrl it will cause errors when trying to open the file in TAS-Editor with some certain inputs. For example, the [R] button doesn't work. There seems to also be a problem with pressing [L] + [ZL] at the same time, but I couldn't confirm this myself.

**Comment by MonsterDruide1** [comment]
As far as I can see, this was a result of the program not handling `KEY_SL` and `KEY_SR` inputs. As Yuzu does not clearly differentiate between those in "normal" dual JoyCon mode, they will end up in the script file too, crashing the editor. This should be fixed now.
