### ISSUE TITLE
Cannot input angle for left stick

### ISSUE THREAD

**Issue by FTSMO** [MonsterDruide1/TAS-editor#55]
https://user-images.githubusercontent.com/100153792/227103604-a6e8e9bb-874e-410c-ade3-1a3f78dda0b6.mp4

When I pasted in a angle and click on the enter key, the automatically changes to 0.

**Comment by MonsterDruide1** [comment]
The `radius` is currently set to 0, so the angle cannot contain a useful value - therefore it resets to 0 instantly.

This is actually expected behaviour, you should set some value for the radius first, before trying to set an angle.
